=== api-evangelist/amadeus-solutions/json-schema/flight-offers-search-flight-filters-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amadeus-solutions/refs/heads/main/json-schema/flight-offers-search-flight-filters-schema.json",
  "title": "FlightFilters",
  "description": "FlightFilters schema",
  "type": "object",
  "properties": {
    "crossBorderAllowed": {
      "description": "Allows to search a location outside the borders when a radius around a location is specified. Default is false.",
      "type": "boolean",
      "example": false
    },
    "moreOvernightsAllowed": {
      "description": "This flag enables/disables the possibility to have more overnight flights in Low Fare Search",
      "type": "boolean",
      "example": false
    },
    "returnToDepartureAirport": {
      "description": "This option force to retrieve flight-offer with a departure and a return in the same airport",
      "type": "boolean",
      "example": false
    },
    "railSegmentAllowed": {
      "description": "This flag enable/disable filtering of rail segment (TGV AIR, RAIL ...)",
      "type": "boolean",
      "example": true
    },
    "busSegmentAllowed": {
      "description": "This flag enable/disable filtering of bus segment",
      "type": "boolean",
      "example": true
    },
    "maxFlightTime": {
      "description": "Maximum flight time as a percentage relative to the shortest flight time available for the itinerary",
      "type": "number",
      "example": 200
    },
    "carrierRestrictions": {
      "title": "CarrierRestrictions",
      "description": "Restriction towards carriers.",
      "$ref": "#/definitions/CarrierRestrictions"
    },
    "cabinRestrictions": {
      "title": "CabinRestrictions",
      "description": "Restriction towards cabins.",
      "type": "array",
      "minItems": 1,
      "maxItems": 6,
      "items": {
        "$ref": "#/definitions/Extended_CabinRestriction"
      }
    },
    "connectionRestriction": {
      "title": "ConnectionRestriction",
      "description": "Restriction towards number of connections.",
      "$ref": "#/definitions/ConnectionRestriction"
    }
  }
}

=== api-evangelist/amadeus-solutions/examples/flight-offers-search-flight-filters-example.json
{
  "crossBorderAllowed": false,
  "moreOvernightsAllowed": false,
  "returnToDepartureAirport": false,
  "railSegmentAllowed": true,
  "busSegmentAllowed": true,
  "maxFlightTime": 200,
  "carrierRestrictions": "AA",
  "cabinRestrictions": [
    "ECONOMY"
  ],
  "connectionRestriction": "sample-value"
}
