=== api-evangelist/amadeus-solutions/json-schema/flight-offers-search-flight-offer-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amadeus-solutions/refs/heads/main/json-schema/flight-offers-search-flight-offer-schema.json",
  "title": "FlightOffer",
  "description": "FlightOffer schema",
  "type": "object",
  "properties": {
    "type": {
      "type": "string",
      "description": "the resource name",
      "example": "flight-offer"
    },
    "id": {
      "description": "Id of the flight offer",
      "type": "string",
      "example": "1"
    },
    "source": {
      "$ref": "#/definitions/FlightOfferSource"
    },
    "instantTicketingRequired": {
      "description": "If true, inform that a ticketing will be required at booking step.",
      "type": "boolean",
      "example": false
    },
    "disablePricing": {
      "description": "BOOK step ONLY - If true, allows to book a PNR without pricing. Only for the source \"GDS\"",
      "type": "boolean",
      "example": false
    },
    "nonHomogeneous": {
      "description": "If true, upon completion of the booking, this pricing solution is expected to yield multiple records (a record contains booking information confirmed and stored, typically a Passenger Name Record (PNR), in the provider GDS or system)",
      "type": "boolean",
      "example": false
    },
    "oneWay": {
      "description": "If true, the flight offer can be combined with other oneWays flight-offers to complete the whole journey (one-Way combinable feature).",
      "type": "boolean",
      "example": false
    },
    "paymentCardRequired": {
      "description": "If true, a payment card is mandatory to book this flight offer",
      "type": "boolean",
      "example": false
    },
    "lastTicketingDate": {
      "description": "If booked on the same day as the search (with respect to timezone), this flight offer is guaranteed to be thereafter valid for ticketing until this date (included). Unspecified when it does not make sense for this flight offer (e.g. no control over ticketing once booked). YYYY-MM-DD format, e.g. 2019-06-07",
      "type": "string",
      "example": "2018-06-19"
    },
    "lastTicketingDateTime": {
      "description": "If booked on the same day as the search (with respect to timezone), this flight offer is guaranteed to be thereafter valid for ticketing until this date/time (included). Unspecified when it does not make sense for this flight offer (e.g. no control over ticketing once booked). Information only this attribute is not used in input of pricing request. Local date and time in YYYY-MM-ddThh:mm:ss format, e.g. 2017-02-10T20:40:00",
      "type": "string",
      "format": "date-time",
      "example": "2018-06-19T15:00:00"
    },
    "numberOfBookableSeats": {
      "description": "Number of seats bookable in a single request. Can not be higher than 9.",
      "type": "number",
      "example": 9,
      "minimum": 1,
      "maximum": 9
    },
    "itineraries": {
      "type": "array",
      "minItems": 1,
      "maxItems": 250,
      "items": {
        "title": "Itineraries",
        "type": "object",
        "properties": {
          "duration": {
            "description": "duration in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) PnYnMnDTnHnMnS format, e.g. PT2H10M for a duration of 2h10m",
            "type": "string",
            "example": "PT2H10M"
          },
          "segments": {
            "title": "Segments",
            "type": "array",
            "minItems": 1,
            "maxItems": 9,
            "items": {
              "$ref": "#/definitions/Segment"
            }
          }
        },
        "required": [
          "segments"
        ]
      }
    },
    "price": {
      "$ref": "#/definitions/Extended_Price"
    },
    "pricingOptions": {
      "title": "PricingOptions",
      "type": "object",
      "properties": {
        "fareType": {
          "description": "type of fare of the flight-offer",
          "$ref": "#/definitions/PricingOptionsFareType"
        },
        "includedCheckedBagsOnly": {
          "type": "boolean",
          "description": "If true, returns the flight-offers with included checked bags only",
          "example": true
        },
        "refundableFare": {
          "type": "boolean",
          "description": "If true, returns the flight-offers with refundable fares only",
          "example": true
        },
        "noRestrictionFare": {
          "type": "boolean",
          "description": "If true, returns the flight-offers with no restriction fares only",
          "example": true
        },
        "noPenaltyFare": {
          "type": "boolean",
          "description": "If true, returns the flight-offers with no penalty fares only",
          "example": true
        }
      }
    },
    "validatingAirlineCodes": {
      "description": "This option ensures that the system will only consider offers with these airlines as validating carrier.",
      "type": "array",
      "minItems": 1,
      "maxItems": 9,
      "items": {
        "type": "string"
      },
      "example": [
        "AF"
      ]
    },
    "travelerPricings": {
      "title": "TravelerPricings",
      "description": "Fare information for each traveler/segment",
      "type": "array",
      "minItems": 1,
      "maxItems": 18,
      "items": {
        "title": "TravelerPricing",
        "required": [
          "travelerId",
          "fareOption",
          "travelerType",
          "fareDetailsBySegment"
        ],
        "properties": {
          "travelerId": {
            "type": "string",
            "example": "1",
            "description": "Id of the traveler"
          },
          "fareOption": {
            "$ref": "#/definitions/TravelerPricingFareOption"
          },
          "travelerType": {
            "$ref": "#/definitions/TravelerType"
          },
          "associatedAdultId": {
            "type": "string",
            "description": "if type=\"HELD_INFANT\", corresponds to the adult traveler's id who will share the seat"
          },
          "price": {
            "description": "price detail of the traveler",
            "$ref": "#/definitions/Price"
          },
          "fareDetailsBySegment": {
            "type": "array",
            "minItems": 1,
            "maxItems": 18,
            "items": {
              "title": "FareDetailsBySegment",
              "description": "Fare details of the segment",
              "required": [
                "segmentId"
              ],
              "properties": {
                "segmentId": {
                  "type": "string",
                  "example": "1",
                  "description": "Id of the segment"
                },
                "cabin": {
                  "$ref": "#/definitions/TravelClass"
                },
                "fareBasis": {
                  "description": "Fare basis specifying the rules of a fare. Usually, though not always, is composed of the booking class code followed by a set of letters and digits representing other characteristics of the ticket, such as refundability, minimum stay requirements, discounts or special promotional elements.",
                  "type": "string",
                  "example": "ANNNNF4K",
                  "pattern": "[[A-Z0-9]{1,18}"
                },
                "brandedFare": {
                  "description": "The name of the Fare Family corresponding to the fares. Only for the GDS provider and if the airline has fare families filled",
                  "type": "string",
                  "example": "LIGHTONE"
                },
                "class": {
                  "description": "The code of the booking class, a.k.a. class of service or Reservations/Booking Designator (RBD)",
                  "type": "string",
                  "example": "A",
                  "pattern": "[A-Z]{1}"
                },
                "isAllotment": {
                  "description": "True if the corresponding booking class is in an allotment",
                  "type": "boolean",
                  "example": true
                },
                "allotmentDetails": {
                  "$ref": "#/definitions/AllotmentDetails"
                },
                "sliceDiceIndicator": {
                  "$ref": "#/definitions/SliceDiceIndicator"
                },
                "includedCheckedBags": {
                  "title": "includedCheckedBags",
                  "$ref": "#/definitions/BaggageAllowance",
                  "description": "Details of the included checked bags"
                },
                "additionalServices": {
                  "type": "object",
                  "title": "AdditionalServicesRequest",
                  "properties": {
                    "chargeableCheckedBags": {
                      "title": "chargeableCheckedBags",
                      "description": "Details of chargeable checked bags",
                      "$ref": "#/definitions/ChargeableCheckdBags"
                    },
                    "chargeableSeat": {
                      "title": "chargeableSeat",
                      "description": "Details of chargeable seat",
                      "$ref": "#/definitions/ChargeableSeat"
                    },
                    "chargeableSeatNumber": {
                      "type": "string",
                      "description": "DEPRECATED - use the chargeableSeat attribute -  seat number",
                      "example": "33D",
                      "pattern": "[1-9][0-9]{0,2}[A-Z]?"
                    },
                    "otherServices": {
                      "type": "array",
                      "description": "Other services to add",
                      "items": {
                        "$ref": "#/definitions/ServiceName"
                      },
                      "example": [
                        "PRIORITY_BOARDING"
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "required": [
    "type",
    "id"
  ]
}

=== api-evangelist/amadeus-solutions/examples/branded-fares-upsell-flight-offer-example.json
{
  "type": "flight-offer",
  "id": "1",
  "source": "sample-value",
  "instantTicketingRequired": false,
  "disablePricing": false,
  "nonHomogeneous": false,
  "oneWay": false,
  "paymentCardRequired": false,
  "lastTicketingDate": "2018-06-19",
  "lastTicketingDateTime": "2018-06-19T15:00:00",
  "numberOfBookableSeats": 9,
  "itineraries": [
    {
      "duration": "PT2H10M",
      "segments": [
        "sample-value"
      ]
    }
  ],
  "price": "299.99",
  "pricingOptions": {
    "fareType": "STANDARD",
    "includedCheckedBagsOnly": true,
    "refundableFare": true,
    "noRestrictionFare": true,
    "noPenaltyFare": true
  },
  "validatingAirlineCodes": [
    "AF"
  ],
  "travelerPricings": [
    "sample-value"
  ]
}
